version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my_network
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mariadb", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "SHOW DATABASES;" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  filler:
    build:
      context: ./filler
    container_name: filler
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data.csv:/app/data.csv

  web:
    build:
      context: ./web
    container_name: web
    depends_on:
      db:
        condition: service_healthy
      filler:
        condition: service_started
    networks:
      - my_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8000:8000"

networks:
  my_network:
    driver: bridge
